### ISSUE TITLE
TextInput is not being whitelisted on iOS using SmartLookSensitiveComponent

### ISSUE THREAD

**Issue by Muzzamil75** [smartlook/smartlook-mobile-issue-tracker#142]
**Platform**
iOS

**Technology**
React-Native : 0.64.2

**Smartlook SDK version**
v1.2.5

**Steps to reproduce **
Wrapping TextInput in SmartLookSensitiveComponent does not make visible TexTField in iOS even with v1.2.5.

Kindly Recheck
@krystofcelba

**Comment by krystofcelba** [comment]
Hey @Muzzamil75,
I've just tried to reproduce your issue so I've set up the initial React Native project with the same RN version as you - `0.64.2` with this snippet to test it.:

```javascript
<SmartlookSensitiveComponent isSensitive={false}>
  <TextInput
    style={styles.input}
    onChangeText={onChangeText}
    value={text}
  />
</SmartlookSensitiveComponent>
```
And it seems it works to me.

Maybe the issue is that you have cached some old Cocoapods version of your package?
Could you please do a backup of your project and then run these commands at the root of your project to install fresh versions of all pods?

```zsh
$ rm -rf ~/Library/Caches/CocoaPods && cd ios && rm -rf Pods && rm -rf ~/Library/Developer/Xcode/DerivedData/* && pod deintegrate && pod setup && pod install
```

**Comment by Muzzamil75** [comment]
@krystofcelba  it does not worked for me !

**Comment by krystofcelba** [comment]
Hey @Muzzamil75,
could you please update to v1.2.6? It should be fixed there.

**Comment by SenNeonoveNoci** [comment]
@Muzzamil75 We are closing our GitHub issues and migrating all issue resolving to Intercom. If you have any further issues please write a follow up on **support@smartlook.com**.
