### ISSUE TITLE
Smartlook.registerBlacklistedView is not working

### ISSUE THREAD

**Issue by matiushenkoa** [smartlook/smartlook-mobile-issue-tracker#31]
**Platform**
IOS

**Technology**
React native

**Smartlook SDK version**
0.37.0

**Summary**
`Smartlook.registerBlacklistedView` is not working, sensitive data is not hiding.

**Comment by pavel-kroh-smartlook** [comment]
Hi, could you share with us code strips where you call the methods? 

Also, send me please your project API key to email `pavelkroh@smartlook.com` so I can look into the recordings. 

Thanks.

**Comment by matiushenkoa** [comment]
Hey, it's simple as that:

```
const ref = useRef(null);

useEffect(() => {
    Smartlook.registerBlacklistedView(ref.current);
}, []);

const renderHeaderTitle = useCallback((props) => {
  return (
    <View ref={ref}>
      <HeaderTitle {...props} />
    </View>
  );
}, []);
```

On android it works as expected

**Comment by pavel-kroh-smartlook** [comment]
Hi, thanks, looking into it.  First, regarding the rendering mode, this works in my test app

`Smartlook.setRenderingMode("wireframe");`

**Comment by matiushenkoa** [comment]
Thanks. `setRenderingMode` is working, no problems with that

**Comment by pavel-kroh-smartlook** [comment]
Ah sorry, for some reason I thought you referred to rendering modes as not working, too.

I just run quick debugging and it seems that something in React Native engine has changed: we now get `nil` instead of `UIView` reference from the `uiManager viewForReactTag` call (we changed nothing in this part of our bridge for quite a time). 

We will look into it deeply asap. Till a fix is found, the only way to custom hiding sensitive data is switching the rendering mode temporarily.

**Comment by pavel-kroh-smartlook** [comment]
Hi again, @matiushenkoa, we found what went wrong and fixed it. Please upgrade to the plugin version `0.39`, the sensitive views handling should be working there again.

**Comment by matiushenkoa** [comment]
Hi @pavel-kroh-smartlook, seems to be working now, thanks
