### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by jonchoi** [smartlook/smartlook-mobile-issue-tracker#33]
hi have you had any recent reports of a memory leak for the ios sdk?

our app has been “crashing” quite a bit.

**Platform**
iOS

**Technology**

**Rendering [optional]**

**Affected devices [optional]**

**Smartlook SDK version**

**Summary**

**Steps to reproduce [optional]**

**Example Project [optional]**

**Relevant logs and/or screenshots**

**Comment by pavel-kroh-smartlook** [comment]
Hi @jonchoi 

could you please share with us more details about the crashes? Stack traces or similar technical clues would help. 

Did the crashes start with some recent smartlook update? 

Also, send me please your project's API key to email pavelkroh@smartlook.com so we can extract additional information from our backend. 

Thank you.

**Comment by SKMaurya1992** [comment]
Hi,
We are facing some performance issues which we think are because of Smartlook SDK.

1) UI Apis are getting called from background threads which ideally should only be called from Main threads. It's causing delay in our applications and sometime Lottie animations also get stucks in between. Mostly observed in Splash screen.

![image](https://user-images.githubusercontent.com/35099968/102469207-7bab2900-4078-11eb-8827-2eeef1c0cab6.png)

2) Getting memory leaks when application is analyzed from XCode instruments software. There are lots of Smartlook delegates and selector which are not getting deallocating properly and causes memory issues.

![image](https://user-images.githubusercontent.com/35099968/102469274-8f568f80-4078-11eb-96c1-8af6d1b7852e.png)


Thanks,
Suraj Kumar

**Comment by pavel-kroh-smartlook** [comment]
Hi @SKMaurya1992 , 

1. this is a debugger warning that does not affect the published apps: https://github.com/smartlook/smartlook-mobile-issue-tracker/issues/33#issuecomment-747322336

2. We are aware about this leak, it will be fixed in the next release soon.

**Comment by pavel-kroh-smartlook** [comment]
Hi @SKMaurya1992 , version 1.7.1 released today addresses the memory leaks.
