### ISSUE TITLE
Build failure on react-native iOS on arm64 Mac - Smartlook-xcframeworks.sh: line 35: ARCHS: unbound variable

### ISSUE THREAD

**Issue by AndrewMorsillo** [smartlook/smartlook-mobile-issue-tracker#60]
**Platform**
iOS

**Technology**
react-native

**Build instructions [optional]**
react native 0.63.3
smartlook-react-native-wrapper 0.39.0

**Smartlook SDK version**
smartlook-react-native-wrapper 0.39.0

**Summary**
Build fails with Xcode 12.4 on an arm64 (Apple m1) Mac. 

```
/Users/imagio/dev/TaskHero/ios/Pods/Target Support Files/Smartlook/Smartlook-xcframeworks.sh: line 35: ARCHS: unbound variable
Selected xcframework slice /Users/imagio/dev/TaskHero/ios/Pods/Smartlook/Smartlook.xcframework
rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" "/Users/imagio/dev/TaskHero/ios/Pods/Smartlook/Smartlook.xcframework//Users/imagio/dev/TaskHero/ios/Pods/Smartlook/Smartlook.xcframework/" "/Users/imagio/Library/Developer/Xcode/DerivedData/TaskHero-efkslfhcxjniutdzjxvvbjpasblj/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/Smartlook"
building file list ... rsync: link_stat "/Users/imagio/dev/TaskHero/ios/Pods/Smartlook/Smartlook.xcframework//Users/imagio/dev/TaskHero/ios/Pods/Smartlook/Smartlook.xcframework/." failed: No such file or directory (2)
done

```

**Steps to reproduce [optional]**
Build a react native project with smart look on an arm64 Mac

**Comment by pavel-kroh-smartlook** [comment]
Hi @AndrewMorsillo , this file is generated by Cocopods, not by us. As Cocopods failed to support pods with arm64 simulators so we removed arm64 simulators from the xcframework so it could be used for Pods at all. Now it seems that Cocoapods are somehow updated to workaround this, so we have to start investigating again to find what and how works.

**Comment by AndrewMorsillo** [comment]
@pavel-kroh-smartlook I see. As a react native dev I have little knowledge of Xcode build system and CocoaPods so I'm not sure about how to work around the issue for now. Is there a way to disable Smartlook only for debug builds in the simulator? I don't want to remove Smartlook from the project but I need to get the project running on my arm64 Mac for development ASAP.

**Comment by pavel-kroh-smartlook** [comment]
Hi @AndrewMorsillo , the build will perhaps work when targeting real device, not a simulator. I'm looking into it right now, if there is a straightforward fix, we will release it (or publish a workaround advice) later this week.

**Comment by pavel-kroh-smartlook** [comment]
Hi again @AndrewMorsillo, just released new Cocoapod (1.7.3) that should solve this (added amr64 simulator back to Cocoapod as they seem to support it now). Let us know, please, if it works for you.

**Comment by AndrewMorsillo** [comment]
@pavel-kroh-smartlook Unfortunately I use a few other libraries that fail to compile for the same reason. Can you describe the changes needed to make this work on the arm64 simulator so I can open more useful issues with them? Thanks!

**Comment by pavel-kroh-smartlook** [comment]
Hi @AndrewMorsillo , 

first, what is behind the issue: the binary distributed libraries must be compiled for the respective architecture(s) where it will be used. 

For long time, there were two architectures: arm64 - the architecture of Apple devices, and x86_64 - the architecture of simulators (i.e., Macs computers). With introduction of M1 chips, there are arm64 computers and thus simulators, too. There are various techniques how to put the the arm64 and x86_64 into one library and hence into one Cocoapod. Some of the older ways work, however, no more in the current environment.

Our solution is as follows:

1. Latest version of Cocoapods should be installed.
 
2. for the binary distributed framework, [Apple XCFramework Bundle](https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages), that contains all architectures, is used. The format is the same as when used in Swift packages. / Note: this did not work originally with Cocoapods when both x86 and amr64 simulator binaries were present in the framework, but seems working now

3. No architecture is excluded in Cocoapod podspec or XCFramework project configurations. In Internet, there are various workarounds described, that in order to make Cocoapods working recommend excluding the arm64 simulator architecture in the configurations. This makes the app compilable for devices, but the app then obviously did not compile or run for simulators on M1 Macs. 

HTH
