### ISSUE TITLE
Smarlook SDK topping memory budget specially on lower-end devices

### ISSUE THREAD

**Issue by alejandro-vori** [smartlook/smartlook-mobile-issue-tracker#93]
**Platform**
iOS

**Technology**
native

**Affected devices [optional]**
iPod Touch 6th gen, iPod Touch 7th gen, among others

**Smartlook SDK version**
1.7.6.1 (latest)

**Summary**
We noticed an arising issue in which the memory budget is exhausted after a few minutes of navigating through our app's screens. We profiled our app hoping to find memory issues on our code base and came across the **SLNativeSnapshotRenderer** using way too much memory. This led to the app being suspended by the system on numerous reports. We ended up setting up a feature flag to put affected users behind it to bypass the Smartlook initialization on our code base. We wanted to inform you about this issue hoping to get a more clear understanding on why this might be happening since it's impacting our user base a lot (a big portion of our customers have legacy devices like the ones I mentioned previously)

Should you require more information please let me know how can I help :)

**Relevant logs and/or screenshots**

This is the exponential memory growth we profiled, please note this is only 400+ MB but I got to almost a GB of memory, from which almost 85% was due to the **SLNativeSnapshotRenderer** object:

![Screenshot at Jul 21 15-30-09 (1)](https://user-images.githubusercontent.com/79858916/126666947-36f8c802-b64b-4a6f-8814-8b0bcfd884e9.png)

![image (1)](https://user-images.githubusercontent.com/79858916/126666965-92657c52-247a-400a-9b69-f658300fc3fb.png)

**Comment by pavel-kroh-smartlook** [comment]
Hi @alejandro-vori , thanks for the detailed report.  We'll discuss your findings here to try finding some better strategy how to make Smartlook feasible for legacy devices, we try to make Smartlook footprint on the app as small as possible, but on weaker devices it is quite hard.

**Comment by jCharv** [comment]
Hi @alejandro-vori, sorry for the late response. I've been doing some tests, and it seems that Xcode Allocations Profiler might be showing wrong data when profiling on older iOS versions (12.5.4 tested). Therefore you might have come to the wrong conclusion that Smartlook is causing those memory pressure crashes. Are you sure that disabling Smartlook fixes those memory pressure crashes you mentioned?

Here is a proof that Allocations profiler might be giving wrong information on older iOSes:

Here is a run done on my test app on iPhone 6+ (iOS 12.5.4, Xcode 12.5.1) where I managed to "allocate" over 10 gigs on a device with 1GB of RAM. (btw the high cpu usage is caused by very high framerate setting)
![what](https://user-images.githubusercontent.com/3813078/128508050-49cf6e6d-29ae-47b0-a84d-160fa2bd8869.jpg)

Here is the same scenario, iPhone6+, but data shown from Xcode memory report instead of allocations profiler:
![xcode6+](https://user-images.githubusercontent.com/3813078/128508664-4dff1a1f-00db-48b5-96a2-158faca4f0f3.jpg)

Same run, but on iPhone Xs:
![Xs](https://user-images.githubusercontent.com/3813078/128508731-2cee6121-037c-403e-913c-78e039ea343e.jpg)

Please let me know if this helps you in any way.
