### ISSUE TITLE
Problem using 'trackNavigationEvent' on iOS

### ISSUE THREAD

**Issue by kislasi** [smartlook/smartlook-mobile-issue-tracker#97]
I'm trying to implement 'trackNavigationEvent' on iOS application (NativeScript application with Smartlook cocoapod) but with no success.
I have tried:
`trackNavigationEventWithControllerId("EVENT_NAME", SLNavigationTypeEnter)`
but SLNavigationTypeEnter is undefined.

can you share with me an example in objective-c?

**Comment by vaclav-halik-smartlook** [comment]
Hello @kislasi,
i will need to know a few more details to help us:

1. What version of our SDK do you use?
2. Please show me sample code/screenshot of ViewController in which you are trying to use these methods.

Then we'll look at what the problem might be.

**Comment by kislasi** [comment]
Hi Vaclav,

as I said we using NativeScript (JavaScript) which using cocoapods (so i'm guessing latest version).

some code samples from our project that WORKS:
`
Smartlook.setupWithKey(apiKey);
Smartlook.startRecording();
..
Smartlook.setUserIdentifier(userId);
..
Smartlook.setRenderingModeTo(SLRenderingModeNoRendering);`

and the only function that we have problem with is: 'trackNavigationEvent'

thanks!

**Comment by vaclav-halik-smartlook** [comment]
Thank you. I understand now, you are trying to use our native SDK from NativeScript. Unfortunately, using the SDK in this way is not currently supported. This does not mean that it will not be possible in the future. We are adding this task to the backlog.

**From a brief investigation:**
The problem is probably caused by incorrect or broken translation of global constants from Objective-C to NativeScript. This would also explain the error message you mentioned.

In Cocoapod package are header file with definition for this constants:
```objc
// MARK: - Custom navigation events

 NS_SWIFT_NAME(Smartlook.NavigationEventType)
 typedef NSString * SLNavigationType NS_TYPED_ENUM;
 extern SLNavigationType const _Nonnull SLNavigationTypeEnter NS_SWIFT_NAME(enter);
 extern SLNavigationType const _Nonnull SLNavigationTypeExit NS_SWIFT_NAME(exit);
```

If you were able to resolve this issue before we did, please contact Support with a link to this issue. They will be able to provide you with some benefit or addition to your monthly subscription.

**Comment by kislasi** [comment]
Hi @vaclav-halik-smartlook 

i'm still trying to solve this issue, maybe you can provide us with a working example in objective-c?
BTW, can I replace 'SLNavigationTypeEnter' with a string value?

thanks

**Comment by pavel-kroh-smartlook** [comment]
Hi @kislasi , yes, literal string values should work now, however, it is not guaranteed that they will not break in the future. The values are `enter` and `exit`.

**Comment by kislasi** [comment]
Hi @pavel-kroh-smartlook,
I've tried using the string value and i'm getting the following error:
`Smartlook.trackNavigationEventWithControllerId is not a function`

**Comment by SenNeonoveNoci** [comment]
@kislasi Sadly `NativeScript` is currently not directly supported by Smartlook. I'm afraid the option, for now, is to write your custom "bridge".

**Comment by pavel-kroh-smartlook** [comment]
Just a technical note: `trackNavigationEventWithControllerId` is indeed an ObjC API function in Smartlook's public API.
